import { Inter_Tight } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";

const inter = Inter_Tight({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
        {children}
        </Provider>
        </body>
    </html>
  );
}
